# Generated by Django 5.2 on 2025-10-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Bu kullanıcının aktif olarak kabul edilip edilmeyeceğini belirtir.', verbose_name='aktif'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='doğrulama kodu'),
        ),
    ]
