# Generated by Django 5.2 on 2025-10-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acusinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Film Başlığı')),
                ('director', models.CharField(max_length=100, verbose_name='Yönetmen')),
                ('release_date', models.DateField(verbose_name='Yayın Tarihi')),
                ('genre', models.CharField(choices=[('DRAM', 'Dram'), ('GERILIM', 'Gerilim'), ('BILIM_KURGU', 'Bilim Kurgu'), ('MACERA', 'Macera'), ('KOMEDI', 'Komedi'), ('AKSIYON', 'Aksiyon'), ('FANTASTIK', 'Fantastik'), ('KORKU', 'Korku')], default='DRAM', max_length=20, verbose_name='Tür')),
                ('duration', models.PositiveIntegerField(help_text='Filmin süresini dakika cinsinden girin.', verbose_name='Süre (dakika)')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Filmin puanını girin (Örn: 8.5).', max_digits=3, verbose_name='Puan')),
                ('poster', models.ImageField(help_text='Filmin afişini yükleyin.', upload_to='posters/', verbose_name='Afiş')),
            ],
            options={
                'verbose_name': 'Acusinema Filmi',
                'verbose_name_plural': 'Acusinema Filmleri',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Etkinlik Başlığı')),
                ('slug', models.SlugField(blank=True, help_text='Bu alan otomatik olarak doldurulacaktır.', max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('event_date', models.DateTimeField(verbose_name='Etkinlik Tarihi ve Saati')),
                ('location', models.CharField(choices=[('K_SALONU', 'Konferans Salonu'), ('ACIK_HAVA', 'Açık Hava Sineması')], default='K_SALONU', max_length=10, verbose_name='Konum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['event_date'],
            },
        ),
    ]
