# Generated by Django 5.2 on 2025-10-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acusinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Film Başlığı')),
                ('director', models.CharField(max_length=100, verbose_name='Yönetmen')),
                ('release_date', models.DateField(verbose_name='Yayın Tarihi')),
            ],
            options={
                'verbose_name': 'Acusinema Filmi',
                'verbose_name_plural': 'Acusinema Filmleri',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Etkinlik Başlığı')),
                ('slug', models.SlugField(blank=True, help_text='Bu alan otomatik olarak doldurulacaktır.', max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('event_date', models.DateTimeField(verbose_name='Etkinlik Tarihi ve Saati')),
                ('location', models.CharField(choices=[('K_SALONU', 'Konferans Salonu'), ('ACIK_HAVA', 'Açık Hava Sineması')], default='K_SALONU', max_length=10, verbose_name='Konum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['event_date'],
            },
        ),
    ]
