# Generated by Django 5.2 on 2025-10-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acusinema',
            name='director',
        ),
        migrations.RemoveField(
            model_name='acusinema',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
