# Generated by Django 5.2 on 2025-10-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta Adresi 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_iframe_src',
            field=models.URLField(blank=True, null=True, verbose_name='Google Harita Gömme (iframe src) Linki'),
        ),
    ]
