# Generated by Django 5.2 on 2025-10-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_address_alter_sitesettings_email1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acusinema',
            name='is_showing_on_homepage',
            field=models.BooleanField(default=False, help_text="Bu filmi anasayfadaki 'Vizyondaki Filmler' bölümünde göstermek için işaretleyin.", verbose_name='Anasayfada Göster'),
        ),
        migrations.AlterField(
            model_name='acusinema',
            name='genre',
            field=models.CharField(choices=[('DRAM', 'Dram'), ('KOMEDI', 'Komedi')], default='DRAM', max_length=20, verbose_name='Tür'),
        ),
    ]
