# Generated by Django 5.2 on 2025-10-13 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acusinema_is_showing_on_homepage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acusinema',
            options={'ordering': ['-created_at'], 'verbose_name': 'Acusinema Filmi', 'verbose_name_plural': 'Acusinema Filmleri'},
        ),
        migrations.RemoveField(
            model_name='acusinema',
            name='is_showing_on_homepage',
        ),
        migrations.AddField(
            model_name='acusinema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Eklenme Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acusinema',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='Tür'),
        ),
    ]
