# Generated by Django 5.2 on 2025-10-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_acusinema_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Slider'da gösterilecek resim (Önerilen boyut: 1200x600 piksel).", upload_to='slider_images/', verbose_name='Slider Resmi')),
                ('title', models.CharField(help_text='Resmin alt etiketi (SEO için önemli).', max_length=200, verbose_name='Başlık')),
                ('order', models.PositiveIntegerField(default=0, help_text='Resimlerin gösterilme sırası (küçükten büyüğe).', verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, help_text="Bu resim slider'da gösterilsin mi?", verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Slider Resmi',
                'verbose_name_plural': 'Slider Resimleri',
                'ordering': ['order'],
            },
        ),
    ]
