# Generated by Django 5.2 on 2025-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sliderimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acusinema',
            options={'ordering': ['-created_at'], 'verbose_name': 'Acusinema Movie', 'verbose_name_plural': 'Acusinema Movies'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['order'], 'verbose_name': 'Slider Image', 'verbose_name_plural': 'Slider Images'},
        ),
        migrations.AlterField(
            model_name='acusinema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='acusinema',
            name='duration',
            field=models.PositiveIntegerField(help_text='Enter the movie duration in minutes.', verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='acusinema',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='acusinema',
            name='poster',
            field=models.ImageField(help_text='Upload the movie poster.', upload_to='posters/', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='acusinema',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='Enter the movie rating (e.g., 8.5).', max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='acusinema',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Movie Title'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Sent'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='Event Date and Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('CONFERENCE_HALL', 'Conference Hall'), ('OPEN_AIR_CINEMA', 'Open-Air Cinema')], default='CONFERENCE_HALL', max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address 2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_iframe_src',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps Embed (iframe src) Link'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(help_text='Image to be displayed in the slider.', upload_to='slider_images/', verbose_name='Slider Image'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Should this image be shown in the slider?', verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order of images (from small to large).', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(help_text='Image alt text (important for SEO).', max_length=200, verbose_name='Title'),
        ),
    ]
