# Generated by Django 5.2 on 2025-10-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_iframe_src',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Maps Embed (iframe src) Link'),
        ),
    ]
